title: Matemática Industrial
description: Página do curso da Universidade Federal do Ceará (UFC)
theme: minima

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
exclude:
  - arquivos-apoio/